### PR TITLE
Speech filtering

### PR DESCRIPTION
**Pull request by beydogan**

### CODE REVIEW

**Comment by beydogan** [comment]
2015-03-09 18:20 GMT+02:00 Zafer CAKMAK <notifications@github.com>:

> Merged #99 <https://github.com/kodgemisi/confdeck/pull/99>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kodgemisi/confdeck/pull/99#event-248650715>.
>

fdsafdasfdsafdsafdsac ommennttt

**Comment by beydogan** [comment]
> dasdjasjdjsjdfdsa

Comment 1952915912

2015-03-12 10:34 GMT+02:00 Mehmet Beydoğan mbbrain@gmail.com:

**Comment by xaph** [comment]
huloooo

**Comment by beydogan** [comment]
comment

**Comment by beydogan** [comment]
fdsadfdfsa

**Pull request merged**
